In [1]:
import matplotlib.pyplot as plt

import numpy as np

import keras

from keras.datasets import mnist

from keras.models import Sequential

from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers import Dropout

from keras.utils.np_utils import to_categorical

from PIL import Image

Using TensorFlow backend.


In [2]:
#carrega o banco de dados do mnist

(xTrain, yTrain), (xTest, yTest) = mnist.load_data()

In [3]:
#xTrain
#len(xTrain)
#xTrain.shape
#yTrain
#yTrain.shape

In [4]:
#One-hot encoding
yTeste = to_categorical(yTest)
yTreino = to_categorical(yTrain)
print(yTreino[0])
print(yTreino[1])
print(yTreino[2])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
#visualizando exemplo de imagem

data = xTrain[0]
img = Image.fromarray(data, 'L') #'L' para imagem em escala de cinza (8-bit)

#img

In [6]:
w, h = 32,32
img = img.resize((w,h), Image.ANTIALIAS)
img

a = np.asarray(img)

img = Image.fromarray(a, 'L') #'L' para imagem em escala de cinza (8-bit)
#img

In [7]:
#ajuste das dimensões das imagens de treino

w, h = 32, 32

auxList = []

for i in range(len(xTrain)):
    
    img = Image.fromarray(xTrain[i], 'L') #'L' para imagem em escala de cinza (8-bit)

    img = img.resize((w,h), Image.ANTIALIAS)
    
    auxList.append(np.asarray(img))

xTreino = np.array(auxList)        
#xTreino.shape

xTreino = xTreino.reshape((60000,32,32,1))

In [8]:
np.array_equal(xTreino[0], xTreino[3])

False

In [9]:
#ajuste das dimensões das imagens de teste

w, h = 32, 32

auxList = []

for i in range(len(xTest)):
    
    img = Image.fromarray(xTest[i], 'L') #'L' para imagem em escala de cinza (8-bit)

    img = img.resize((w,h), Image.ANTIALIAS)

    auxList.append(np.asarray(img))

xTeste = np.array(auxList)
#xTeste.shape

xTeste = xTeste.reshape((10000, 32, 32, 1))

In [10]:
'''#visualizando exemplo de imagem

data = xTreino[0]
img = Image.fromarray(data, 'L') #'L' para imagem em escala de cinza (8-bit)

#print(data.shape)
img'''

"#visualizando exemplo de imagem\n\ndata = xTreino[0]\nimg = Image.fromarray(data, 'L') #'L' para imagem em escala de cinza (8-bit)\n\n#print(data.shape)\nimg"

In [ ]:
def leNet():
    
    classificador = Sequential()
    
    #imagem 32x32
    #Camada convolucional 1
    classificador.add(Conv2D(filters = 6, kernel_size = 5, strides = 1, activation = 'relu', kernel_initializer='random_uniform', input_shape = (32,32,1)))
    
    #imagem 28x28
    #Camada de pooling 1
    classificador.add(MaxPooling2D(pool_size = 2, strides = 2))
    
    #imagem 14x14
    #Camada convolucional 2
    classificador.add(Conv2D(filters = 16, kernel_size = 5, strides = 1, activation = 'relu', kernel_initializer='random_uniform', input_shape = (14,14,6)))
    
    #imagem 10x10
    #Camada de pooling 2
    classificador.add(MaxPooling2D(pool_size = 2, strides = 2))
    
    #imagem 5x5
    #Flatten
    classificador.add(Flatten())
    
    #Camada totalmente conectada 1
    classificador.add(Dense(units = 120, activation = 'relu', kernel_initializer='random_uniform'))
    
    #Camada totalmente conectada 2
    classificador.add(Dense(units = 84, activation = 'relu',  kernel_initializer='random_uniform',))
    
    #Camada de saída
    classificador.add(Dense(units = 10, activation = 'softmax',  kernel_initializer='random_uniform',))
    
    classificador.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
    
    return  classificador

In [ ]:
model = leNet()
#print(xTreino.shape)
history = model.fit(xTreino, yTreino, validation_split=0.16665, epochs=50, batch_size=32, initial_epoch=-1)

Train on 50001 samples, validate on 9999 samples
Epoch 0/50
50001/50001 [==============================] - 53s 1ms/step - loss: 0.1425 - acc: 0.9549 - val_loss: 0.0682 - val_acc: 0.9805
Epoch 1/50
50001/50001 [==============================] - 53s 1ms/step - loss: 0.0579 - acc: 0.9826 - val_loss: 0.0528 - val_acc: 0.9849
Epoch 2/50
50001/50001 [==============================] - 61s 1ms/step - loss: 0.0465 - acc: 0.9856 - val_loss: 0.0572 - val_acc: 0.9829
Epoch 3/50
50001/50001 [==============================] - 62s 1ms/step - loss: 0.0398 - acc: 0.9883 - val_loss: 0.0501 - val_acc: 0.9869
Epoch 4/50
50001/50001 [==============================] - 59s 1ms/step - loss: 0.0334 - acc: 0.9905 - val_loss: 0.0599 - val_acc: 0.9836
Epoch 5/50
50001/50001 [==============================] - 57s 1ms/step - loss: 0.0320 - acc: 0.9905 - val_loss: 0.0525 - val_acc: 0.9872
Epoch 6/50
50001/50001 [==============================] - 54s 1ms/step - loss: 0.0268 - acc: 0.9920 - val_loss: 0.0580 - val_acc:

In [ ]:
# Plot training & validation accuracy values
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Val'], loc='upper left')
plt.show()

In [ ]:
# Plot training & validation loss values
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Val'], loc='upper left')
plt.show()

In [ ]:
pred = model.predict(xTeste)

In [ ]:
pred[0]

In [ ]:
cont = 0
correto = 0
incorreto = 0
for ele in yTeste:
    if np.array_equal(ele, pred[cont]):
        correto += 1
    else:
        incorreto += 1
    cont += 1
    
print(correto)
print(incorreto)
print(correto/(incorreto+correto))